In [13]:
import numpy as np
import pandas as pd 
import os
import requests
import json 
from bs4 import BeautifulSoup
import boto3
from IPython.display import HTML, display
import time

In [14]:
url="https://rehos.cuni.cz/crpp/eshop/index"
headers={"User-Agent": "Anna_Chodurkova (Educational access; contact: chodurkovaanna@gmail.com)"}

In [15]:
r=requests.get(url,headers=headers)
r.text

'<!DOCTYPE html>\n<html>\n  <head>\n    <title>Centrální prodejní a rezervační portál ubytování na kolejích UK | Centrální prodejní a rezervační portál ubytování na kolejích UK</title>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>\n    <meta name="Description" content="Centr&aacute;ln&iacute; prodejn&iacute; a rezervačn&iacute; port&aacute;l ubytov&aacute;n&iacute; na kolej&iacute;ch UK"/>\n    <link rel="stylesheet" href="/crpp/css/default.css" />\n    <link rel="stylesheet" href="/crpp/css/content.css" />\n    <link rel="stylesheet" href="/crpp/css/header.css" />\n    <link rel="stylesheet" href="/crpp/css/footer.css" />\n    <link rel="stylesheet" href="/crpp/css/main.css" />\n    <link rel="shortcut icon" href="/crpp/images/favicon.ico" type="image/x-icon" />\n    \n<!--<link rel="stylesheet" href="/crpp/css/jquery-ui-1.8.9.custom.css"/>-->\n<script src="/crpp/js/console-log-reset.js"></script>\n<link rel="shortcut icon" href="/crpp/images/favicon.ico" type="image/x-icon"/>\n<script src="/crpp/plugins/jquery-1.8.3/js/jquery/jquery-1.8.3.min.js" type="text/javascript" library="jquery"></script>\r\n\n\n\n<script type="text/javascript" src="/crpp/js/jquery/jquery.ui.datepicker-cs.js"></script>\n<link href="/crpp/jquery-ui/themes/smoothness/jquery-ui-1.8.11.custom.css" type="text/css" rel="stylesheet" /><script src="/crpp/plugins/jquery-ui-1.8.24/jquery-ui/js/jquery-ui-1.8.24.custom.min.js" type="text/javascript" ></script>\n\n\n\n\n\n\n\n<!-- Official jqgrid resources -->\n\n<!-- TODO: Missing way hot to override locale -->\n<link href="/crpp/plugins/jqgrid-3.8.0.1/css/jqgrid/ui.jqgrid.css" rel="stylesheet" type="text/css" />\n<link href="/crpp/plugins/jqgrid-3.8.0.1/css/jqgrid/jqgrid.css" rel="stylesheet" type="text/css" />\n<script src="/crpp/plugins/jqgrid-3.8.0.1/js/jqgrid/i18n/grid.locale-cs.js"></script>\n<script src="/crpp/plugins/jqgrid-3.8.0.1/js/jqgrid/jquery.jqGrid.min.js"></script>\n<script src="/crpp/plugins/jqgrid-3.8.0.1/js/jqgrid/jquery.jqGrid.fluid.js"></script>\n\n<script src="/crpp/js/application.js" type="text/javascript"></script>\r\n\n<link rel=\'stylesheet\' type=\'text/css\' href=\'/crpp/plugins/export-1.0/css/export.css\' />\n<link href="/crpp/js/tooltip/jquery.bubblepopup.v2.3.1.css" rel="stylesheet" type="text/css" />\n<script src="/crpp/js/tooltip/jquery.bubblepopup.v2.3.1.min.js"></script>\n\n<link href="/crpp/js/tinydropdown2/tinydropdown.css" rel="stylesheet" type="text/css" />\n<script src="/crpp/js/tinydropdown2/tinydropdown-packed.js"></script>\n\n<script src="/crpp/js/loading.js"></script>\n<script src="/crpp/js/tableSpliter.js"></script>\n<script src="/crpp/js/input-checkboxizer.js"></script>\n<script src="/crpp/js/input-filler.js"></script>\n<script src="/crpp/js/ys-date.js"></script>\n<script src="/crpp/js/objectFormatters.js"></script>\n\n<!-- Google tag (gtag.js) -->\n<script async src="https://www.googletagmanager.com/gtag/js?id=G-X19QQXJMRV"></script>\n<script>\nwindow.dataLayer = window.dataLayer || [];\nfunction gtag(){dataLayer.push(arguments);}\ngtag(\'js\', new Date());\n\ngtag(\'config\', \'G-X19QQXJMRV\');\n</script>\n    \n    \n    <meta name="layout" content="main"/>\n    <script>\n        $(function () {\n            $("#tabs").tabs();\n        });\n\n        $(document).ready(function () {\n            $(\'li.hentry:has(a)\').click(function () {\n                $(this).addClass(\'linked\');\n                /*Allows for CSS hover and different styles for link clicks.*/\n                window.location = $(\'a\', $(this)).attr(\'href\');\n            }); //End Click\n        }); //End OnReady\n\n\n    </script>\n\n\n    <ga:trackPageview></ga:trackPageview>\n</head>\n\n\n\n<body class="notloggedin">\n  <div id="main-div">\n\n    \n<div id="header">\n  <div id="banner">\n    \n\n<div id="toolbar">\n  <ul>\n    \n    \n    \n    \n    \n\n    \n    <li><a href="/crpp/login/index">přihlásit se</a></li>\n    <li><a href="/crpp/accountRegistration/index">registrovat</a></li>\n\n    \n    \n    \n        <li><a href="/crpp/help/before">první informace</a></li>\n        <li class="last"><a href="/crpp/help/index">nápověda</a></li>\n    \n  </ul>\n</div>\n\n    <div id="logo"><a href="/crpp/"><img src="/crpp/images/logo-shadow.png" alt="CUNI" border="0" /></a></div>\n    <div class="content">Centrální prodejní a rezervační portál ubytování na kolejích UK</div>\n  </div>\n  \n\n<div id="top_nav" class="nav">\n    <ul id="top-nav-menu" class="menu">\n        \n            <li class="home"><li><a href="/crpp/">Domů</a></li>\n            <li class="home"><li><a href="/crpp/eshop/index">Volné kapacity</a></li>\n            <li class="home"><li><a href="/crpp/accommodation/index">Stávající ubytování</a></li>\n            <li class="faq"><a href="/crpp/faqAdmin/listPublic">FAQ</a></li>\n\n            \n        \n\n        \n\n\n\n        \n\n        \n\n        \n        \n        \n\n    </ul>\n\n    <div class="clearing"></div>\n</div>\n\n<script type="text/javascript">\n    var dropdown = new TINY.dropdown.init("dropdown", {id: \'top-nav-menu\', active: \'menuhover\'});\n</script>\n\n</div>\n\n    <div id="content-container">\n      <div class="content">\n\n<h1>Přehled volných kolejí</h1>\n\n\n<p></p>\n<div class="message">\n<p>Na této stránce jsou zobrazeny jednotlivé koleje a jejich orientační volné kapacity. Pro vytvoření rezervace ubytování klepněte na obrázek koleje.</p>\n</div>\n\n\n\n<div id="tabs" style="border: 0 solid #AAA;">\n    <ul style="border: 0 solid #AAA;border-bottom-width: 1px;background: white;">\n        \n            <li><a href="#tabs-PH">Praha</a></li>\n        \n            <li><a href="#tabs-PL">Plzeň</a></li>\n        \n            <li><a href="#tabs-HK">Hradec Králové</a></li>\n        \n            <li><a href="#tabs-BL">Brandýs nad Labem</a></li>\n        \n    </ul>\n    \n        <div id="tabs-PH">\n            <div id="collegeTiles" class="">\n                <ul>\n                    \n                        \n                            \n                        \n                    \n                        \n                    \n                        \n                            \n                                <li class="hentry">\n                                    <div class="college" style="text-align: center">\n                                        <h3>Budeč</h3>\n                                        <img style="width: 120px"\n                                             src="/crpp/images/college/KAM-47-version1-Budec_kolej_134.jpg"\n                                             alt="Kolej" />\n                                        <a href="/crpp/eshop/collegeDetail/380942" style="display: none">Volná lůžka</a>\n                                        <div style="display: none;">\n                                            <table class="form" style="width : 100%; font-size: 12px;">\n\n                                                <tbody>\n                                                <tr>\n                                                    \n                                                    \n                                                    \n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top; font-size: 8px; text-align: center">Muži</td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top;font-size: 8px; text-align: center">Ženy</td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top;font-size: 8px; text-align: center">Neurčeno</td>\n                                                </tr>\n                                                <tr style="color: green">\n                                                    \n                                                    \n                                                    \n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top;text-align: center"><b>0</b>\n                                                    </td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top; text-align: center"><b>0</b>\n                                                    </td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top; text-align: center"><b>0</b>\n                                                    </td>\n                                                </tr>\n\n\n                                                \n                                                    \n                                                    \n                                                    \n                                                    \n\n                                                    \n                                                    \n                                                    \n\n                                                    \n                                                    \n                                                    \n\n                                                    \n                                                    \n                                                \n\n\n\n\n                                                </tbody>\n                                            </table>\n\n                                        </div>\n                                    </div>\n                                </li>\n                            \n                        \n                    \n                        \n                    \n                        \n                            \n                                <li class="hentry">\n                                    <div class="college" style="text-align: center">\n                                        <h3>Hostivař</h3>\n                                        <img style="width: 120px"\n                                             src="/crpp/images/college/KAM-47-version1-kolej_Hostivar_2115.jpg"\n                                             alt="Kolej" />\n                                        <a href="/crpp/eshop/collegeDetail/380952" style="display: none">Volná lůžka</a>\n                                        <div style="display: none;">\n                                            <table class="form" style="width : 100%; font-size: 12px;">\n\n                                                <tbody>\n                                                <tr>\n                                                    \n                                                    \n                                                    \n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top; font-size: 8px; text-align: center">Muži</td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top;font-size: 8px; text-align: center">Ženy</td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top;font-size: 8px; text-align: center">Neurčeno</td>\n                                                </tr>\n                                                <tr style="color: green">\n                                                    \n                                                    \n                                                    \n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top;text-align: center"><b>0</b>\n                                                    </td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top; text-align: center"><b>0</b>\n                                                    </td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top; text-align: center"><b>0</b>\n                                                    </td>\n                                                </tr>\n\n\n                                                \n                                                    \n                                                    \n                                                    \n                                                    \n\n                                                    \n                                                    \n                                                    \n\n                                                    \n                                                    \n                                                    \n\n                                                    \n                                                    \n                                                \n\n\n\n\n                                                </tbody>\n                                            </table>\n\n                                        </div>\n                                    </div>\n                                </li>\n                            \n                        \n                    \n                        \n                            \n                                <li class="hentry">\n                                    <div class="college" style="text-align: center">\n                                        <h3>Hvězda</h3>\n                                        <img style="width: 120px"\n                                             src="/crpp/images/college/KAM-47-version1-Hvezda_197.jpg"\n                                             alt="Kolej" />\n                                        <a href="/crpp/eshop/collegeDetail/380944" style="display: none">Volná lůžka</a>\n                                        <div style="display: none;">\n                                            <table class="form" style="width : 100%; font-size: 12px;">\n\n                                                <tbody>\n                                                <tr>\n                                                    \n                                                    \n                                                    \n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top; font-size: 8px; text-align: center">Muži</td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top;font-size: 8px; text-align: center">Ženy</td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top;font-size: 8px; text-align: center">Neurčeno</td>\n                                                </tr>\n                                                <tr style="color: green">\n                                                    \n                                                    \n                                                    \n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top;text-align: center"><b>0</b>\n                                                    </td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top; text-align: center"><b>0</b>\n                                                    </td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top; text-align: center"><b>3</b>\n                                                    </td>\n                                                </tr>\n\n\n                                                \n                                                    \n                                                    \n                                                    \n                                                    \n\n                                                    \n                                                    \n                                                    \n\n                                                    \n                                                    \n                                                    \n\n                                                    \n                                                    \n                                                \n\n\n\n\n                                                </tbody>\n                                            </table>\n\n                                        </div>\n                                    </div>\n                                </li>\n                            \n                        \n                    \n                        \n                    \n                        \n                            \n                                <li class="hentry">\n                                    <div class="college" style="text-align: center">\n                                        <h3>Jednota</h3>\n                                        <img style="width: 120px"\n                                             src="/crpp/images/college/KAM-47-version1-kolej_Opletalova_117.jpg"\n                                             alt="Kolej" />\n                                        <a href="/crpp/eshop/collegeDetail/380939" style="display: none">Volná lůžka</a>\n                                        <div style="display: none;">\n                                            <table class="form" style="width : 100%; font-size: 12px;">\n\n                                                <tbody>\n                                                <tr>\n                                                    \n                                                    \n                                                    \n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top; font-size: 8px; text-align: center">Muži</td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top;font-size: 8px; text-align: center">Ženy</td>\n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top;font-size: 8px; text-align: center">Neurčeno</td>\n                                                </tr>\n                                                <tr style="color: green">\n                                                    \n                                                    \n                                                    \n                                                    <td style="padding: 1px 1px;\n\n                                                    vertical-align: top;text-align: center"><b>2</b>\n                                              

In [16]:
soup=BeautifulSoup(r.text,"html")

In [17]:
dorm_id=[380942,380952,380944,380939,380946,380958,380945,380950,380943,380948,380951,380961]

In [12]:
data=[]
for id in dorm_id:
    url=f"https://rehos.cuni.cz/crpp/eshop/collegeDetail/{id}"
    soup=BeautifulSoup(requests.get(url).content,"html.parser")
    #find dorm name
    dorm_name = soup.find("h1").text.strip()
    
    #find room data
    table = soup.find("table", {"class": "form"})
    #loop through each table row 
    for row in table.find_all("tr"):
        #find all cells
        cols = row.find_all("td")
        #avoid header rows
        if len(cols) >= 2:
            #data, clean
            data.append({
                "dorm": dorm_name,
                "room_type": cols[0].text.strip().split("\n")[0].lower(),
                "price": cols[1].text.strip().split("\n")[0]
            })
    time.sleep(1)

In [26]:
#further cleaning
df=pd.DataFrame(data)
df

                   dorm                           room_type price
0           Kolej Budeč       1-lůžkový pokoj bez soc. zař.   230
1           Kolej Budeč       2-lůžkový pokoj bez soc. zař.   176
2           Kolej Budeč       3-lůžkový pokoj bez soc. zař.   146
3        Kolej Hostivař        1-lůžkový pokoj se soc. zař.   196
4        Kolej Hostivař       2-lůžkový pokoj bez soc. zař.   151
5        Kolej Hostivař        2-lůžkový pokoj se soc. zař.   164
6          Kolej Hvězda       1-lůžkový pokoj bez soc. zař.   198
7          Kolej Hvězda       2-lůžkový pokoj bez soc. zař.   155
8          Kolej Hvězda        2-lůžkový pokoj se soc. zař.   242
9          Kolej Hvězda        1-lůžkový pokoj se soc. zař.   269
10         Kolej Hvězda    1-lůžkový pokoj bez soc. zař. nw   219
11         Kolej Hvězda  2-lůžkový pokoj bez soc. zař. nwxl   168
12        Kolej Jednota       1-lůžkový pokoj bez soc. zař.   232
13        Kolej Jednota       2-lůžkový pokoj bez soc. zař.   193
14        Kolej Jednota       3-lůžkový pokoj bez soc. zař.   154
15        Kolej Jednota       4-lůžkový pokoj bez soc. zař.   144
16        Kolej Jednota       5-lůžkový pokoj bez soc. zař.     0
17      Kolej Kajetánka        1-lůžkový pokoj se soc. zař.   233
18      Kolej Kajetánka        2-lůžkový pokoj se soc. zař.   183
19      Kolej Kajetánka     2-lůžkový pokoj se soc. zař. nw   183
20      Kolej Kajetánka     1-lůžkový pokoj se soc. zař. nw   244
21      Kolej Kajetánka   1-lůžkový pokoj se soc. zař. nwxl   269
22     Kolej Komenského        1-lůžkový pokoj se soc. zař.   267
23     Kolej Komenského        2-lůžkový pokoj se soc. zař.     0
24     Kolej Komenského     1-lůžkový pokoj se soc. zař. nw   272
25     Kolej Komenského     2-lůžkový pokoj se soc. zař. nw   226
26    Kolej Na Větrníku       1-lůžkový pokoj bez soc. zař.   190
27    Kolej Na Větrníku       2-lůžkový pokoj bez soc. zař.   140
28    Kolej Na Větrníku       3-lůžkový pokoj bez soc. zař.   126
29          Kolej Otava        1-lůžkový pokoj se soc. zař.   198
30          Kolej Otava        2-lůžkový pokoj se soc. zař.   153
31          Kolej Otava        3-lůžkový pokoj se soc. zař.   146
32          Kolej Otava     2-lůžkový pokoj se soc. zař. nw   176
33          Kolej Otava     1-lůžkový pokoj se soc. zař. nw   215
34       Kolej Švehlova       1-lůžkový pokoj bez soc. zař.   176
35       Kolej Švehlova       2-lůžkový pokoj bez soc. zař.   148
36       Kolej Švehlova       3-lůžkový pokoj bez soc. zař.   119
37       Kolej Švehlova        3-lůžkový pokoj se soc. zař.   119
38       Kolej Švehlova       4-lůžkový pokoj bez soc. zař.   107
39  Kolej 17. listopadu        2-lůžkový pokoj se soc. zař.   174
40         Kolej Vltava         1-lůžkový pokoj se soc.zař.   198
41         Kolej Vltava        2-lůžkový pokoj se soc. zař.   153
42         Kolej Vltava     1-lužkový pokoj se soc. zar. nw   215
43        Kolej Krystal       1-lůžkový pokoj se soc. zař.    444
44        Kolej Krystal        2-lůžkový pokoj se soc. zař.   310

In [29]:
df = df[df["price"].astype(int) != 0]

for index, row in df.iterrows():
    if 'nw' in row['room_type'] or 'nwxl' in row['room_type']:
        df = df.drop(index)

df = df.reset_index(drop=True)
df

                   dorm                      room_type price
0           Kolej Budeč  1-lůžkový pokoj bez soc. zař.   230
1           Kolej Budeč  2-lůžkový pokoj bez soc. zař.   176
2           Kolej Budeč  3-lůžkový pokoj bez soc. zař.   146
3        Kolej Hostivař   1-lůžkový pokoj se soc. zař.   196
4        Kolej Hostivař  2-lůžkový pokoj bez soc. zař.   151
5        Kolej Hostivař   2-lůžkový pokoj se soc. zař.   164
6          Kolej Hvězda  1-lůžkový pokoj bez soc. zař.   198
7          Kolej Hvězda  2-lůžkový pokoj bez soc. zař.   155
8          Kolej Hvězda   2-lůžkový pokoj se soc. zař.   242
9          Kolej Hvězda   1-lůžkový pokoj se soc. zař.   269
10        Kolej Jednota  1-lůžkový pokoj bez soc. zař.   232
11        Kolej Jednota  2-lůžkový pokoj bez soc. zař.   193
12        Kolej Jednota  3-lůžkový pokoj bez soc. zař.   154
13        Kolej Jednota  4-lůžkový pokoj bez soc. zař.   144
14      Kolej Kajetánka   1-lůžkový pokoj se soc. zař.   233
15      Kolej Kajetánka   2-lůžkový pokoj se soc. zař.   183
16     Kolej Komenského   1-lůžkový pokoj se soc. zař.   267
17    Kolej Na Větrníku  1-lůžkový pokoj bez soc. zař.   190
18    Kolej Na Větrníku  2-lůžkový pokoj bez soc. zař.   140
19    Kolej Na Větrníku  3-lůžkový pokoj bez soc. zař.   126
20          Kolej Otava   1-lůžkový pokoj se soc. zař.   198
21          Kolej Otava   2-lůžkový pokoj se soc. zař.   153
22          Kolej Otava   3-lůžkový pokoj se soc. zař.   146
23       Kolej Švehlova  1-lůžkový pokoj bez soc. zař.   176
24       Kolej Švehlova  2-lůžkový pokoj bez soc. zař.   148
25       Kolej Švehlova  3-lůžkový pokoj bez soc. zař.   119
26       Kolej Švehlova   3-lůžkový pokoj se soc. zař.   119
27       Kolej Švehlova  4-lůžkový pokoj bez soc. zař.   107
28  Kolej 17. listopadu   2-lůžkový pokoj se soc. zař.   174
29         Kolej Vltava    1-lůžkový pokoj se soc.zař.   198
30         Kolej Vltava   2-lůžkový pokoj se soc. zař.   153
31        Kolej Krystal  1-lůžkový pokoj se soc. zař.    444
32        Kolej Krystal   2-lůžkový pokoj se soc. zař.   310

In [30]:
df.to_csv("dorm_prices.csv",index=False)

In [31]:
df=pd.read_csv("dorm_prices.csv")
df

                   dorm                      room_type  price
0           Kolej Budeč  1-lůžkový pokoj bez soc. zař.    230
1           Kolej Budeč  2-lůžkový pokoj bez soc. zař.    176
2           Kolej Budeč  3-lůžkový pokoj bez soc. zař.    146
3        Kolej Hostivař   1-lůžkový pokoj se soc. zař.    196
4        Kolej Hostivař  2-lůžkový pokoj bez soc. zař.    151
5        Kolej Hostivař   2-lůžkový pokoj se soc. zař.    164
6          Kolej Hvězda  1-lůžkový pokoj bez soc. zař.    198
7          Kolej Hvězda  2-lůžkový pokoj bez soc. zař.    155
8          Kolej Hvězda   2-lůžkový pokoj se soc. zař.    242
9          Kolej Hvězda   1-lůžkový pokoj se soc. zař.    269
10        Kolej Jednota  1-lůžkový pokoj bez soc. zař.    232
11        Kolej Jednota  2-lůžkový pokoj bez soc. zař.    193
12        Kolej Jednota  3-lůžkový pokoj bez soc. zař.    154
13        Kolej Jednota  4-lůžkový pokoj bez soc. zař.    144
14      Kolej Kajetánka   1-lůžkový pokoj se soc. zař.    233
15      Kolej Kajetánka   2-lůžkový pokoj se soc. zař.    183
16     Kolej Komenského   1-lůžkový pokoj se soc. zař.    267
17    Kolej Na Větrníku  1-lůžkový pokoj bez soc. zař.    190
18    Kolej Na Větrníku  2-lůžkový pokoj bez soc. zař.    140
19    Kolej Na Větrníku  3-lůžkový pokoj bez soc. zař.    126
20          Kolej Otava   1-lůžkový pokoj se soc. zař.    198
21          Kolej Otava   2-lůžkový pokoj se soc. zař.    153
22          Kolej Otava   3-lůžkový pokoj se soc. zař.    146
23       Kolej Švehlova  1-lůžkový pokoj bez soc. zař.    176
24       Kolej Švehlova  2-lůžkový pokoj bez soc. zař.    148
25       Kolej Švehlova  3-lůžkový pokoj bez soc. zař.    119
26       Kolej Švehlova   3-lůžkový pokoj se soc. zař.    119
27       Kolej Švehlova  4-lůžkový pokoj bez soc. zař.    107
28  Kolej 17. listopadu   2-lůžkový pokoj se soc. zař.    174
29         Kolej Vltava    1-lůžkový pokoj se soc.zař.    198
30         Kolej Vltava   2-lůžkový pokoj se soc. zař.    153
31        Kolej Krystal  1-lůžkový pokoj se soc. zař.     444
32        Kolej Krystal   2-lůžkový pokoj se soc. zař.    310