In [6]:
import requests

url = "https://kamweb.ruk.cuni.cz/webkredit/Api/Ordering/Menu?Dates=2026-04-14T22%3A00%3A00.000Z&CanteenId=7"

r = requests.get(url)
data = r.json()

print(data)

{'groups': [{'date': '2026-04-14T22:00:00.0000000Z', 'mealKindId': 2, 'mealKindName': 'Polévka', 'rows': [{'item': {'date': '2026-04-14T22:00:00.0000000Z', 'canteenId': 7, 'mealKindId': 2, 'altId': 1, 'mealKindName': 'Polévka', 'mealName': 'Špenátový krém s jáhlami', 'mealSize': None, 'price': 22.0, 'price2': 22.0, 'currency': 'Kč', 'dualPrice': None, 'dualPrice2': None, 'dualCurrency': None, 'inExchange': False, 'state': 111, 'show': True, 'orderInAdvance': False, 'countAvailable': 160, 'countOrdered': 0, 'allergens': 'soja, celer', 'allergensIds': ['958f1e32-3a06-47e6-845d-191bec3a50af', 'c81ec82b-f6bb-42e6-8dfb-80e333fa78ef'], 'allergensShort': ['celer', 'soja'], 'pictograms': [6, 33, 35], 'nutritionalValues': None, 'note': '1 porce: 1 000 kJ / 240 kcal ( Bílkoviny 8 g  Sacharidy 25 g  Tuky 9 g )', 'menuDetailId': None, 'imageId': 0}, 'composites': None}]}, {'date': '2026-04-14T22:00:00.0000000Z', 'mealKindId': 3, 'mealKindName': 'Hlavní jídlo', 'rows': [{'item': {'date': '2026-04-14T22:00:00.0000000Z', 'canteenId': 7, 'mealKindId': 3, 'altId': 1, 'mealKindName': 'Hlavní jídlo', 'mealName': 'Obalovaný losos s medem a hořčicí, bramborová kaše', 'mealSize': '110 g', 'price': 143.0, 'price2': 107.0, 'currency': 'Kč', 'dualPrice': None, 'dualPrice2': None, 'dualCurrency': None, 'inExchange': False, 'state': 5, 'show': True, 'orderInAdvance': True, 'countAvailable': 165, 'countOrdered': 5, 'allergens': 'lepek (pšenice), vejce, ryby, mléko, hořčice', 'allergensIds': ['998f7566-e5b4-4ec2-a616-39af78c3743c', '0657434d-95d6-4341-8eed-3c1c6e204838', '77e8af22-0464-4683-b172-73e1120cfa5e', 'c7ca4215-673f-44e4-a3a9-75f286b55355', '26a10ffd-2c88-4834-9656-d6b66476c46a', '7de11ba9-64de-4c15-963b-dacd24d6d4bb'], 'allergensShort': ['ryby', 'lepek', 'vejce', 'mléko', 'hořčice', 'pšenice'], 'pictograms': [5], 'nutritionalValues': None, 'note': '1 porce: 2235 kJ / 534 kcal  ( Bílkoviny 23 g  Sacharidy 57,7 g  Tuky 24,3 g )', 'menuDetailId': None, 'imageId': 0}, 'composites': None}, {'item': {'date': '2026-04-14T22:00:00.0000000Z', 'canteenId': 7, 'mealKindId': 3, 'altId': 2, 'mealKindName': 'Hlavní jídlo', 'mealName': 'Halušky se zelím a uzeným masem', 'mealSize': '360 g', 'price': 136.0, 'price2': 100.0, 'currency': 'Kč', 'dualPrice': None, 'dualPrice2': None, 'dualCurrency': None, 'inExchange': False, 'state': 5, 'show': True, 'orderInAdvance': True, 'countAvailable': 152, 'countOrdered': 8, 'allergens': 'lepek (pšenice), vejce, mléko, oxid siřičitý', 'allergensIds': ['0657434d-95d6-4341-8eed-3c1c6e204838', 'bcec0578-8aad-4230-b0cf-506a102d6b50', '77e8af22-0464-4683-b172-73e1120cfa5e', 'c7ca4215-673f-44e4-a3a9-75f286b55355', '7de11ba9-64de-4c15-963b-dacd24d6d4bb'], 'allergensShort': ['lepek', 'oxid siřičitý', 'vejce', 'mléko', 'pšenice'], 'pictograms': [3], 'nutritionalValues': None, 'note': '1 porce 2725 kJ / 651 kcal ( Bílkoviny 22 g  Sacharidy 66,4 g Tuky 30,8 g)', 'menuDetailId': None, 'imageId': 0}, 'composites': None}, {'item': {'date': '2026-04-14T22:00:00.0000000Z', 'canteenId': 7, 'mealKindId': 3, 'altId': 3, 'mealKindName': 'Hlavní jídlo', 'mealName': 'Vegetariánská musaka', 'mealSize': '390 g', 'price': 138.0, 'price2': 102.0, 'currency': 'Kč', 'dualPrice': None, 'dualPrice2': None, 'dualCurrency': None, 'inExchange': False, 'state': 5, 'show': True, 'orderInAdvance': True, 'countAvailable': 63, 'countOrdered': 2, 'allergens': 'lepek (pšenice), mléko, oxid siřičitý', 'allergensIds': ['0657434d-95d6-4341-8eed-3c1c6e204838', 'bcec0578-8aad-4230-b0cf-506a102d6b50', 'c7ca4215-673f-44e4-a3a9-75f286b55355', '7de11ba9-64de-4c15-963b-dacd24d6d4bb'], 'allergensShort': ['lepek', 'oxid siřičitý', 'mléko', 'pšenice'], 'pictograms': [6, 34], 'nutritionalValues': None, 'note': '1 porce: 2250 kJ / 538 kcal ( Bílkoviny 18,9 g  Sacharidy 57,9 g  Tuky 26,8 g', 'menuDetailId': None, 'imageId': 0}, 'composites': None}, {'item': {'date': '2026-04-14T22:00:00.0000000Z', 'canteenId': 7, 'mealKindId': 3, 'altId': 4, 'mealKindName': 'Hlavní jídlo', 'mealName': 'Cizrnová paela', 'mealSize': '400 g', 'price': 125.0, 'price2': 78.0, 'currency': 'Kč', 'dualPrice': None, 'dualPrice2': None, 'dualCurrency': None, 'inExchange': False, 'state': 5, 'show': True, 'orderInAdvance': True, 'countAvailable': 44, 'countOrdered': 1, 'allergens': 'celer', 'allergensIds': ['958f1e32-3a06-47e6-845d-191bec3a50af'], 'allergensShort': ['celer'], 'pictograms': [33, 35, 38], 'nutritionalValues': None, 'note': '1 porce: 2 150 kJ / 515 kcal ( Bílkoviny 15 g  Sacharidy 85 g  Tuky 12 g )', 'menuDetailId': None, 'imageId': 0}, 'composites': None}, {'item': {'date': '2026-04-14T22:00:00.0000000Z', 'canteenId': 7, 'mealKindId': 3, 'altId': 5, 'mealKindName': 'Hlavní jídlo', 'mealName': 'Kuřecí medailonky, bramborové hranolky, proteinový bylinkový dip', 'mealSize': '150g', 'price': 154.0, 'price2': 118.0, 'currency': 'Kč', 'dualPrice': None, 'dualPrice2': None, 'dualCurrency': None, 'inExchange': False, 'state': 111, 'show': True, 'orderInAdvance': False, 'countAvailable': 70, 'countOrdered': 0, 'allergens': 'lepek (pšenice), soja, mléko, celer, oxid siřičitý', 'allergensIds': ['958f1e32-3a06-47e6-845d-191bec3a50af', '0657434d-95d6-4341-8eed-3c1c6e204838', 'bcec0578-8aad-4230-b0cf-506a102d6b50', 'c7ca4215-673f-44e4-a3a9-75f286b55355', 'c81ec82b-f6bb-42e6-8dfb-80e333fa78ef', '7de11ba9-64de-4c15-963b-dacd24d6d4bb'], 'allergensShort': ['celer', 'lepek', 'oxid siřičitý', 'mléko', 'soja', 'pšenice'], 'pictograms': [4], 'nutritionalValues': None, 'note': '1 porce: 4452kJ / 1081 kcal ( Bílkoviny 44,2 g Sacharidy 107,1 g Tuky 52,1 g)', 'menuDetailId': None, 'imageId': 0}, 'composites': None}, {'item': {'date': '2026-04-14T22:00:00.0000000Z', 'canteenId': 7, 'mealKindId': 3, 'altId': 7, 'mealKindName': 'Hlavní jídlo', 'mealName': 'Teplý bufet', 'mealSize': None, 'price': 290.0, 'price2': 269.5, 'currency': 'Kč', 'dualPrice': None, 'dualPrice2': None, 'dualCurrency': None, 'inExchange': False, 'state': 111, 'show': True, 'orderInAdvance': False, 'countAvailable': None, 'countOrdered': 0, 'allergens': None, 'allergensIds': None, 'allergensShort': None, 'pictograms': None, 'nutritionalValues': None, 'note': None, 'menuDetailId': None, 'imageId': 0}, 'composites': None}]}], 'pictograms': [{'id': 3, 'name': 'Vepřové maso'}, {'id': 4, 'name': 'Kuřecí maso'}, {'id': 5, 'name': 'Ryba'}, {'id': 6, 'name': 'Česnek'}, {'id': 33, 'name': 'VEGAN'}, {'id': 34, 'name': 'VEGETARIAN'}, {'id': 35, 'name': 'NEOBSAHUJE MOUKU'}, {'id': 38, 'name': 'Peníze'}], 'locale': 'cs', 'results': None}

In [11]:
data 

rows = []

for group in data["groups"]:
    for r in group["rows"]:
        item = r["item"]

        rows.append({
            "meal": item["mealName"],
            "price": item["price2"],
            "type": item["mealKindName"]
        })

In [12]:
import pandas as pd

df = pd.DataFrame(rows)

In [13]:
df.to_csv("menza.csv", index=False)

In [14]:
df

                                                meal  price          type
0                           Špenátový krém s jáhlami   22.0       Polévka
1  Obalovaný losos s medem a hořčicí, bramborová ...  107.0  Hlavní jídlo
2                    Halušky se zelím a uzeným masem  100.0  Hlavní jídlo
3                               Vegetariánská musaka  102.0  Hlavní jídlo
4                                     Cizrnová paela   78.0  Hlavní jídlo
5  Kuřecí medailonky, bramborové hranolky, protei...  118.0  Hlavní jídlo
6                                        Teplý bufet  269.5  Hlavní jídlo

In [1]:
import requests
import pandas as pd
from datetime import datetime, timedelta
import time

base_url = "https://kamweb.ruk.cuni.cz/webkredit/Api/Ordering/Menu"

canteen_id = 7
start = datetime(2026, 4, 14)

all_rows = []

for i in range(7):
    day = start + timedelta(days=i)
    date_str = day.strftime("%Y-%m-%dT22:00:00.000Z")

    r = requests.get(base_url, params={
        "Dates": date_str,
        "CanteenId": canteen_id
    })

    data = r.json()

    for group in data["groups"]:
        if not group.get("rows"):
            continue  # skip empty groups
        for row in group["rows"]:
            item = row["item"]

            all_rows.append({
                "date": group["date"],
                "meal": item["mealName"],
                "price": item["price2"],
                "type": item["mealKindName"]
            })
        time.sleep(1)

df = pd.DataFrame(all_rows)

In [2]:
df

,date,meal,price,type
0,2026-04-14T22:00:00.0000000Z,Špenátový krém s jáhlami,22.0,Polévka
1,2026-04-14T22:00:00.0000000Z,"Obalovaný losos s medem a hořčicí, bramborová ...",107.0,Hlavní jídlo
2,2026-04-14T22:00:00.0000000Z,Halušky se zelím a uzeným masem,100.0,Hlavní jídlo
3,2026-04-14T22:00:00.0000000Z,Vegetariánská musaka,102.0,Hlavní jídlo
4,2026-04-14T22:00:00.0000000Z,Cizrnová paela,78.0,Hlavní jídlo
5,2026-04-14T22:00:00.0000000Z,"Kuřecí medailonky, bramborové hranolky, protei...",118.0,Hlavní jídlo
6,2026-04-14T22:00:00.0000000Z,Teplý bufet,269.5,Hlavní jídlo
7,2026-04-15T22:00:00.0000000Z,Kulajda,22.0,Polévka
8,2026-04-15T22:00:00.0000000Z,"Kuřecí stehno pečené, červené zelí, bramborové...",112.0,Hlavní jídlo
9,2026-04-15T22:00:00.0000000Z,Pad Thai s hovězími nudličkami a rýžovými nudlemi,128.0,Hlavní jídlo
10,2026-04-15T22:00:00.0000000Z,"Smažený květák , vařené brambory, tatarská omáčka",87.0,Hlavní jídlo
11,2026-04-15T22:00:00.0000000Z,Bulgur s grilovanou zeleninou a jogurtovo-byli...,112.0,Hlavní jídlo
12,2026-04-15T22:00:00.0000000Z,"Kuřecí směs pikantní, bramboráčky",111.0,Hlavní jídlo
13,2026-04-15T22:00:00.0000000Z,Teplý bufet,269.5,Hlavní jídlo
14,2026-04-16T22:00:00.0000000Z,Fazolová bílá polévka,22.0,Polévka
15,2026-04-16T22:00:00.0000000Z,"Smažený kuřecí řízek, bramborová kaše, citron",107.0,Hlavní jídlo
16,2026-04-16T22:00:00.0000000Z,Fusilli Tonno,93.0,Hlavní jídlo
17,2026-04-16T22:00:00.0000000Z,"Čočkový dhal, basmati rýže",79.0,Hlavní jídlo
18,2026-04-16T22:00:00.0000000Z,Bramborové knedlíky plněné celou švestkou se s...,121.0,Hlavní jídlo
19,2026-04-16T22:00:00.0000000Z,"Vepřové karé čertovské, americké brambory",110.0,Hlavní jídlo
20,2026-04-16T22:00:00.0000000Z,Teplý bufte,269.5,Hlavní jídlo
21,2026-04-19T22:00:00.0000000Z,Kuřecí vývar s nudlemi,22.0,Polévka
22,2026-04-19T22:00:00.0000000Z,"Kuřecí roláda plněná, dušená rýže",103.0,Hlavní jídlo
23,2026-04-19T22:00:00.0000000Z,"Segedínský guláš, houskový knedlík",95.0,Hlavní jídlo
24,2026-04-19T22:00:00.0000000Z,"Mac and Cheese, malý míchaný salát",99.0,Hlavní jídlo
25,2026-04-19T22:00:00.0000000Z,"Čočkový kotlík, chléb",74.0,Hlavní jídlo
26,2026-04-19T22:00:00.0000000Z,"Vepřová kotleta na grilu, dip, americké brambory",107.0,Hlavní jídlo
27,2026-04-19T22:00:00.0000000Z,Teplý bufet,269.5,Hlavní jídlo
28,2026-04-20T22:00:00.0000000Z,Dršťková polévka z hlívy ústřičné,22.0,Polévka
29,2026-04-20T22:00:00.0000000Z,"Hovězí stoganoff, dušená rýže",115.0,Hlavní jídlo
30,2026-04-20T22:00:00.0000000Z,"Domácí pečená sekaná, bramborová kaše, okurka",102.0,Hlavní jídlo
31,2026-04-20T22:00:00.0000000Z,Kuskusový nákyp se zeleninou,87.0,Hlavní jídlo
32,2026-04-20T22:00:00.0000000Z,Stir Fry rýžové nudle se zeleninou a edamame,115.0,Hlavní jídlo
33,2026-04-20T22:00:00.0000000Z,"Kuřecí stripsy,citrón, hranolky",124.0,Hlavní jídlo
34,2026-04-20T22:00:00.0000000Z,Teplý bufet,269.5,Hlavní jídlo

In [29]:
df.to_csv("menza_week.csv", index=False)

In [30]:
df

,date,meal,price,type
0,2026-04-14T22:00:00.0000000Z,Špenátový krém s jáhlami,22.0,Polévka
1,2026-04-14T22:00:00.0000000Z,"Obalovaný losos s medem a hořčicí, bramborová ...",107.0,Hlavní jídlo
2,2026-04-14T22:00:00.0000000Z,Halušky se zelím a uzeným masem,100.0,Hlavní jídlo
3,2026-04-14T22:00:00.0000000Z,Vegetariánská musaka,102.0,Hlavní jídlo
4,2026-04-14T22:00:00.0000000Z,Cizrnová paela,78.0,Hlavní jídlo
5,2026-04-14T22:00:00.0000000Z,"Kuřecí medailonky, bramborové hranolky, protei...",118.0,Hlavní jídlo
6,2026-04-14T22:00:00.0000000Z,Teplý bufet,269.5,Hlavní jídlo
7,2026-04-15T22:00:00.0000000Z,Kulajda,22.0,Polévka
8,2026-04-15T22:00:00.0000000Z,"Kuřecí stehno pečené, červené zelí, bramborové...",112.0,Hlavní jídlo
9,2026-04-15T22:00:00.0000000Z,Pad Thai s hovězími nudličkami a rýžovými nudlemi,128.0,Hlavní jídlo
10,2026-04-15T22:00:00.0000000Z,"Smažený květák , vařené brambory, tatarská omáčka",87.0,Hlavní jídlo
11,2026-04-15T22:00:00.0000000Z,Bulgur s grilovanou zeleninou a jogurtovo-byli...,112.0,Hlavní jídlo
12,2026-04-15T22:00:00.0000000Z,"Kuřecí směs pikantní, bramboráčky",111.0,Hlavní jídlo
13,2026-04-15T22:00:00.0000000Z,Teplý bufet,269.5,Hlavní jídlo
14,2026-04-16T22:00:00.0000000Z,Fazolová bílá polévka,22.0,Polévka
15,2026-04-16T22:00:00.0000000Z,"Smažený kuřecí řízek, bramborová kaše, citron",107.0,Hlavní jídlo
16,2026-04-16T22:00:00.0000000Z,Fusilli Tonno,93.0,Hlavní jídlo
17,2026-04-16T22:00:00.0000000Z,"Čočkový dhal, basmati rýže",79.0,Hlavní jídlo
18,2026-04-16T22:00:00.0000000Z,Bramborové knedlíky plněné celou švestkou se s...,121.0,Hlavní jídlo
19,2026-04-16T22:00:00.0000000Z,"Vepřové karé čertovské, americké brambory",110.0,Hlavní jídlo
20,2026-04-16T22:00:00.0000000Z,Teplý bufte,269.5,Hlavní jídlo
21,2026-04-19T22:00:00.0000000Z,Kuřecí vývar s nudlemi,22.0,Polévka
22,2026-04-19T22:00:00.0000000Z,"Kuřecí roláda plněná, dušená rýže",103.0,Hlavní jídlo
23,2026-04-19T22:00:00.0000000Z,"Segedínský guláš, houskový knedlík",95.0,Hlavní jídlo
24,2026-04-19T22:00:00.0000000Z,"Mac and Cheese, malý míchaný salát",99.0,Hlavní jídlo
25,2026-04-19T22:00:00.0000000Z,"Čočkový kotlík, chléb",74.0,Hlavní jídlo
26,2026-04-19T22:00:00.0000000Z,"Vepřová kotleta na grilu, dip, americké brambory",107.0,Hlavní jídlo
27,2026-04-19T22:00:00.0000000Z,Teplý bufet,269.5,Hlavní jídlo
28,2026-04-20T22:00:00.0000000Z,Dršťková polévka z hlívy ústřičné,22.0,Polévka
29,2026-04-20T22:00:00.0000000Z,"Hovězí stoganoff, dušená rýže",115.0,Hlavní jídlo
30,2026-04-20T22:00:00.0000000Z,"Domácí pečená sekaná, bramborová kaše, okurka",102.0,Hlavní jídlo
31,2026-04-20T22:00:00.0000000Z,Kuskusový nákyp se zeleninou,87.0,Hlavní jídlo
32,2026-04-20T22:00:00.0000000Z,Stir Fry rýžové nudle se zeleninou a edamame,115.0,Hlavní jídlo
33,2026-04-20T22:00:00.0000000Z,"Kuřecí stripsy,citrón, hranolky",124.0,Hlavní jídlo
34,2026-04-20T22:00:00.0000000Z,Teplý bufet,269.5,Hlavní jídlo

In [38]:
df=df[df["meal"]!="Teplý bufet"]
main_dish=df[df["type"]=="Hlavní jídlo"]
main_dish.price.mean()
main_dish.price.median()

107.0